version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - web_scraping

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - web_scraping
  
  api:
    build: ./app
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis
    networks:
      - web_scraping
  
  worker:
    build: ./worker
    container_name: worker
    depends_on:
      - redis
      - rabbitmq
    networks:
      - web_scraping

networks:
  web_scraping:
    driver: bridge

